services:
  redis:
    image: redis:7.0.9
    hostname: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    container_name: redis
    command: redis-server --port 6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 30s
      timeout: 30s
      retries: 3