version: "3.9"

services:
  mariadb:
    image: mariadb:10.8.3
    hostname: mariadb
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=mariadb
    ports:
      - 3306:3306
    container_name: mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 30s
      retries: 3
