version: "3.9"

services:
  mongodb:
    image: mongo:5.0.10
    hostname: mongodb
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/conf/mongod.conf:/data/conf/mongod.conf
      - ./volume/data:/data/db
      - ./volume/log:/data/log
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
    ports:
      - 27017:27017
    container_name: mongodb
    command: --config /data/conf/mongod.conf
    healthcheck:
       test: ["CMD","mongo", "--eval", "db.adminCommand('ping')"]
       interval: 30s
       timeout: 30s
       retries: 3

