services:
  redis:
    image: redis:7.0.9
    hostname: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    container_name: redis
    command: redis-server --port 6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -p 6379 ping | grep PONG"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  redis_data: